using System.ComponentModel;

namespace RPGMakerUtils.Resources
{
    /// <summary>
    /// Represents common RPG Maker MV/MZ event codes with associated text descriptions.
    /// IMPORTANT NOTE: This enum is generated by AI, please use with caution.
    /// </summary>
    internal enum RPGMakerEventCommandCode
    {

        #region Manually Verified
        /// <summary>
        /// Used to show character names above the text box.
        /// </summary>
        [Description("Show Text")]
        ShowText = 101,

        [Description("Show Choices")]
        ShowChoices = 102,

        /// <summary>
        /// Main text (Dialog or Message)
        /// </summary>
        [Description("Show Text (Continued)")]
        ShowTextContinued = 401,

        [Description("When Choice")]
        WhenChoice = 402,

        /// <summary>
        /// Scrolling text or Display with a window
        /// </summary>
        [Description("Show Text (Name Window)")]
        ShowTextNameWindow = 405,

        /// <summary>
        /// Run a script or code block
        /// </summary>
        [Description("Evaluate Script")]
        EvaluateScript = 355, // Example {"code":355,"indent":1,"parameters":["$dataClasses[2].name = '助手'"]}

        /// <summary>
        /// Run Plugin with Array parameters, First string is the plugin name
        /// </summary>
        [Description("Use Plugin (Array)")]
        PluginArray = 356, // Example {"code":356,"indent":1,"parameters":["PA_INIT 6 4 連番 0"]}

        /// <summary>
        /// Run a function from a plugin You can get the plugin name from parameters.name
        /// </summary>
        [Description("Use Plugin (Object)")]
        PluginObject = 357, // Example 
        #endregion

        [Description("When Cancel")]
        WhenCancel = 403, // Branch for cancelling choices

        [Description("Input Number")]
        InputNumber = 103, // Allows player to input a number

        [Description("Select Item")]
        SelectItem = 104, // Allows player to select an item

        [Description("Show Scrolling Text")]
        ShowScrollingText = 105, // Displays text that scrolls

        // Game Progression and Flow Control
        [Description("Control Switches")]
        ControlSwitches = 121, // Changes the state of switches

        [Description("Control Variables")]
        ControlVariables = 122, // Changes the value of variables

        [Description("Control Self Switch")]
        ControlSelfSwitch = 123, // Changes the state of an event's self switches

        [Description("Control Timer")]
        ControlTimer = 124, // Manages the in-game timer

        [Description("Conditional Branch")]
        ConditionalBranch = 111, // Creates a conditional fork in the event flow

        [Description("Else")]
        ConditionalBranchElse = 411, // The 'else' part of a conditional branch

        [Description("Loop")]
        Loop = 112, // Starts a loop

        [Description("Repeat Above")]
        LoopRepeatAbove = 413, // End of a loop

        [Description("Break Loop")]
        BreakLoop = 113, // Exits the current loop

        [Description("Exit Event Processing")]
        ExitEventProcessing = 114, // Stops the current event

        [Description("Common Event")]
        CommonEvent = 115, // Calls a common event

        [Description("Label")]
        Label = 116, // Defines a jump target

        [Description("Jump to Label")]
        JumpToLabel = 117, // Jumps to a defined label

        [Description("Comment")]
        Comment = 108, // Adds a comment (ignored by game)

        // Party, Actor, and Battle
        [Description("Battle Processing")]
        BattleProcessing = 301, // Starts a battle

        [Description("Shop Processing")]
        ShopProcessing = 302, // Opens a shop

        [Description("Name Input Processing")]
        NameInputProcessing = 303, // Allows player to input a name

        [Description("Change HP")]
        ChangeHP = 311, // Changes an actor's HP

        [Description("Change MP")]
        ChangeMP = 312, // Changes an actor's MP

        [Description("Change State")]
        ChangeState = 313, // Adds or removes a state from an actor

        [Description("Recover All")]
        RecoverAll = 314, // Recovers actor's HP/MP and removes states

        [Description("Change EXP")]
        ChangeEXP = 315, // Changes actor's experience

        [Description("Change Level")]
        ChangeLevel = 316, // Changes actor's level

        [Description("Change Skill")]
        ChangeSkill = 319, // Learns or forgets a skill

        [Description("Change Equipment")]
        ChangeEquipment = 320, // Changes actor's equipment

        [Description("Change Name")]
        ChangeName = 321, // Changes actor's name

        [Description("Change Class")]
        ChangeClass = 322, // Changes actor's class

        [Description("Change Enemy HP")]
        ChangeEnemyHP = 331, // Changes an enemy's HP in battle

        [Description("Change Enemy MP")]
        ChangeEnemyMP = 332, // Changes an enemy's MP in battle

        [Description("Change Enemy State")]
        ChangeEnemyState = 333, // Adds or removes a state from an enemy

        [Description("Enemy Recover All")]
        EnemyRecoverAll = 334, // Recovers enemy's HP/MP and removes states

        [Description("Change Gold")]
        ChangeGold = 340, // Changes party's gold

        [Description("Change Items")]
        ChangeItems = 341, // Changes party's items

        [Description("Change Weapons")]
        ChangeWeapons = 342, // Changes party's weapons

        [Description("Change Armor")]
        ChangeArmor = 343, // Changes party's armor

        [Description("Change Party Members")]
        ChangePartyMembers = 344, // Adds or removes actors from the party

        // Movement
        [Description("Transfer Player")]
        TransferPlayer = 201, // Moves the player

        [Description("Set Vehicle Location")]
        SetVehicleLocation = 202, // Sets vehicle position

        [Description("Set Event Location")]
        SetEventLocation = 203, // Sets event position

        [Description("Scroll Map")]
        ScrollMap = 204, // Scrolls the map view

        [Description("Set Movement Route")]
        SetMovementRoute = 205, // Defines a custom movement route

        [Description("Change Transparency")]
        ChangeTransparency = 211, // Makes character transparent/opaque

        [Description("Change Player Followers")]
        ChangePlayerFollowers = 212, // Shows or hides followers

        [Description("Gather Followers")]
        GatherFollowers = 213, // Makes followers gather

        // Picture
        [Description("Show Picture")]
        ShowPicture = 231, // Displays a picture

        [Description("Move Picture")]
        MovePicture = 232, // Moves a picture

        [Description("Rotate Picture")]
        RotatePicture = 233, // Rotates a picture

        [Description("Tint Picture")]
        TintPicture = 234, // Changes picture color tone

        [Description("Erase Picture")]
        ErasePicture = 235, // Erases a picture

        // Screen
        [Description("Fadeout Screen")]
        FadeoutScreen = 241, // Fades screen to black

        [Description("Fadein Screen")]
        FadeinScreen = 242, // Fades screen in from black

        [Description("Tint Screen")]
        TintScreen = 243, // Changes screen color tone

        [Description("Flash Screen")]
        FlashScreen = 244, // Flashes the screen

        [Description("Shake Screen")]
        ShakeScreen = 245, // Shakes the screen

        [Description("Set Weather Effect")]
        SetWeatherEffect = 236, // Changes weather

        // Audio & Video
        [Description("Play BGM")]
        PlayBGM = 250, // Plays background music

        [Description("Fadeout BGM")]
        FadeoutBGM = 251, // Fades out BGM

        [Description("Play SE")]
        PlaySE = 257, // Plays a sound effect

        [Description("Stop SE")]
        StopSE = 258, // Stops sound effects

        [Description("Play Movie")]
        PlayMovie = 261, // Plays a movie

        // Scene Control
        [Description("Open Menu Screen")]
        OpenMenuScreen = 351, // Opens the menu

        [Description("Open Save Screen")]
        OpenSaveScreen = 352, // Opens the save screen

        [Description("Game Over")]
        GameOver = 353, // Ends the game

        [Description("Return to Title Screen")]
        ReturnToTitleScreen = 354, // Returns to the title

        // System Settings
        [Description("Change Window Color")]
        ChangeWindowColor = 136, // Changes the window color

        // Map
        [Description("Change Map Name Display")]
        ChangeMapNameDisplay = 281, // Shows or hides map name display

        [Description("Change Tileset")]
        ChangeTileset = 282, // Changes the map tileset

        [Description("Change Battle Background")]
        ChangeBattleBackground = 283, // Changes battle background

        [Description("Change Parallax")]
        ChangeParallax = 284, // Changes the parallax background

        [Description("Get Location Info")]
        GetLocationInfo = 285 // Gets information about a map location
    }

}
